name: donationist
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Provides support for various animation types.
  animations: ^2.0.11
  # Implements the BLoC pattern for state management.
  bloc: ^8.1.4
  # Efficiently loads and caches network images.
  cached_network_image: ^3.3.1
  # Monitors network connectivity (WiFi & mobile/cellular).
  connectivity_plus: ^6.0.3
  # Provides Cupertino-style icons for iOS.
  cupertino_icons: ^1.0.8
  # Simplifies equality comparisons for Dart objects.
  equatable: ^2.0.5
  # Adds animation capabilities to Flutter widgets.
  flutter_animate: ^4.5.0
  # Provides BLoC architecture components.
  flutter_bloc: ^8.1.6
  # Generates app launcher icons.
  flutter_launcher_icons: ^0.13.1
  # Generates native splash screens.
  flutter_native_splash: ^2.4.0
  # Helps with responsive UI design.
  flutter_screenutil: ^5.9.3
  # Provides a collection of loading spinners.
  flutter_spinkit: ^5.2.1
  # Customizable toast messages.
  flutter_styled_toast: ^2.2.1
  # Renders SVG images in Flutter.
  flutter_svg: ^2.0.10+1
  # Includes Font Awesome icons.
  font_awesome_flutter: ^10.7.0
  # Dependency injection library.
  get_it: ^8.0.0-pre-5
  # Loads Google Fonts in Flutter.
  google_fonts: ^6.2.1
  # Customizable loading animations.
  loading_animation_widget: ^1.2.1
  # Renders Lottie animations in Flutter.
  lottie: ^3.1.2
  # Provides page transition animations.
  page_transition: ^2.1.0
  # Persists key-value data on the device.
  shared_preferences: ^2.2.3
  # Adds smooth page indicators for carousels.
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  # Lint rules for Flutter code
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
